// Interface texts by language - kept in sync with bt-ctd-echo
export const interfaceTexts = {
  fr: {
    title: 'echo',
    subtitle: 'Studio de modèles intelligents',
    selectTemplate: 'Sélectionnez un modèle',
    templatesCount: `modèles disponibles`,
    searchPlaceholder: 'Rechercher un modèle...',
    allCategories: 'Toutes les catégories',
    categories: {
      clarifications_and_client_instructions: 'Précisions et instructions client',
      deadlines_and_delivery: 'Délais et livraisons',
      documents_and_formatting: 'Documents et formats',
      follow_ups_and_cancellations: 'Suivi et annulations',
      quotes_and_approvals: 'Devis et approbations',
      security_and_copyright: 'Sécurité et droits d\'auteur'
    },
    templateLanguage: 'Langue du modèle',
    interfaceLanguage: 'Langue de l\'interface',
    variables: 'Variables',
    editEmail: 'Éditez votre modèle',
    subject: 'Objet',
    body: 'Corps du message',
    reset: 'Réinitialiser',
    copy: 'Copier',
    copySubject: 'Copier Objet',
    copyBody: 'Copier Corps', 
    copyAll: 'Copier Tout',
    copied: 'Copié !',
    copyLink: 'Copier le lien',
    copyLinkTitle: 'Copier le lien direct vers ce modèle',
    openInOutlookClassic: 'Ouvrir dans Outlook classique',
    openInOutlookClassicTitle: 'Composer avec Outlook classique',
    openInOutlookWeb: 'Ouvrir dans Outlook Web',
    openInOutlookWebTitle: 'Composer avec Outlook Web',
    sendEmail: 'Envoyer',
    favorites: 'Favoris',
    showFavoritesOnly: 'Afficher uniquement les favoris',
    noTemplate: 'Sélectionnez un modèle pour commencer',
    resetWarningTitle: 'Confirmer la réinitialisation',
    resetWarningMessage: 'Êtes-vous sûr de vouloir réinitialiser toutes les variables ? Cette action ne peut pas être annulée.',
    cancel: 'Annuler',
    confirm: 'Confirmer'
  },
  en: {
    title: 'echo',
    subtitle: 'Smart Template Studio',
    selectTemplate: 'Select a template',
    templatesCount: `templates available`,
    searchPlaceholder: 'Search for a template...',
    allCategories: 'All categories',
    categories: {
      clarifications_and_client_instructions: 'Clarifications and client instructions',
      deadlines_and_delivery: 'Deadlines and delivery',
      documents_and_formatting: 'Documents and formatting',
      follow_ups_and_cancellations: 'Follow-ups and cancellations',
      quotes_and_approvals: 'Quotes and approvals',
      security_and_copyright: 'Security and copyright'
    },
    templateLanguage: 'Template language',
    interfaceLanguage: 'Interface language',
    variables: 'Variables',
    editEmail: 'Edit your template',
    subject: 'Subject',
    body: 'Message body',
    reset: 'Reset',
    copy: 'Copy',
    copySubject: 'Copy Subject',
    copyBody: 'Copy Body',
    copyAll: 'Copy All',
    copied: 'Copied!',
    copyLink: 'Copy link',
    copyLinkTitle: 'Copy direct link to this template',
    openInOutlookClassic: 'Open in Outlook Classic',
    openInOutlookClassicTitle: 'Compose in Outlook Classic',
    openInOutlookWeb: 'Open in Outlook Web',
    openInOutlookWebTitle: 'Compose in Outlook Web',
    sendEmail: 'Send',
    favorites: 'Favorites',
    showFavoritesOnly: 'Show only favorites',
    noTemplate: 'Select a template to get started',
    resetWarningTitle: 'Confirm Reset',
    resetWarningMessage: 'Are you sure you want to reset all variables? This action cannot be undone.',
    cancel: 'Cancel',
    confirm: 'Confirm'
  }
}
